application:
  name: open-camping-api
  project: Open Camping API
  organization: QoveryCommunity
  port: 4000
  dockerfile: api/Dockerfile
  cpu: 1
  ram: 1GB
databases:
  - type: MONGODB
    name: open-camping-db
    version: 4.4
routers:
  - name: main
    routes:
      - application_name: open-camping-api
        paths:
          - /
