application:
  name: camping-api
  project: Camping API
  organization: QoveryCommunity
  port: 4000
  dockerfile: api/Dockerfile
databases:
  - type: MONGODB
    name: camping-db
    version: 4.4
routers:
  - name: main
    routes:
      - application_name: camping-api
        paths:
          - /
